package mastermind;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;

public class Highscore
{
	private static final String ID = "id";
	private static final String NAME = "name";
	private static final String SCORE = "score";
	private static final String TABLE_NAME = "highscore";
	private static final String SCHEMA = "APP";
	private static final String CREATE_TABLE_STM = "CREATE TABLE " + TABLE_NAME + "("
			+ ID + " INT NOT NULL GENERATED BY DEFAULT AS IDENTITY, "
			+ NAME + " VARCHAR(32), "
			+ SCORE + " BIGINT, "
			+ "PRIMARY Key(" + ID + "))";
	
	private static Connection createConnection() throws ClassNotFoundException, SQLException
	{
		Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
		Connection connection = DriverManager.getConnection("jdbc:derby:../highscore; create=true");
		return connection;
	}
	
	public static boolean createTable()
	{
		boolean created = true;
		try{
			Connection connection = createConnection();
			DatabaseMetaData metaData = connection.getMetaData();
			ResultSet tables = metaData.getTables(null, SCHEMA, TABLE_NAME, null);
			if(!tables.next())
			{
				try{
					Statement statement = connection.createStatement();
					statement.executeUpdate(CREATE_TABLE_STM);
					statement.close();
					System.out.println("Tabelle wurde neu erstellt.");
				}catch(SQLException e){
					System.out.println("Tabelle bereits vorhanden: " + e.getMessage());
					created = false;
				}
			}
		}catch(ClassNotFoundException e){
			System.out.println("Treiberproblem: " + e.getMessage());
		}catch(SQLException e){
			System.out.println("Datenbankproblem: " + e.getMessage());
		}
		return created;
	}
	
	public static boolean insertIntoHighscore(String name, long score)
	{
		boolean inserted = false;
		try{
			Connection connection = createConnection();
			Statement insertStm = connection.createStatement();
			insertStm.executeUpdate("INSERT INTO " + TABLE_NAME + " (" + NAME + ", " + SCORE + ") VALUES('" + name + "', " + score + ")");
			insertStm.close();
			System.out.println("Eingefügt: " + name);
			inserted = true;
		}catch(ClassNotFoundException e){
			System.out.println("Treiberproblem: " + e.getMessage());
		}catch(SQLException e){
			System.out.println("Fehler beim Einfügen: " + e.getMessage());
		}
		return inserted;
	}
	
	public static Map<String, Long> readHighscore()
	{
		Map<String, Long> dataSet = new HashMap<>();
		try{
			Connection connection = createConnection();
			Statement statement = connection.createStatement();
			ResultSet result = statement.executeQuery("SELECT * FROM " + TABLE_NAME);
			while(result.next())
			{
				String name = result.getString(NAME);
				long score = result.getLong(SCORE);
				dataSet.put(name, score);
			}
		}catch(ClassNotFoundException e){
			System.out.println("Treiberproblem: " + e.getMessage());
		}catch(SQLException e){
			System.out.println("Fehler beim Lesen: " + e.getMessage());
		}
		return dataSet;
	}
	
	public static void main(String[] args)
	{
		test2();
	}
	
	@SuppressWarnings("unused")
	private static void test1()
	{
		createTable();
		insertIntoHighscore("Chris", 100000);
		insertIntoHighscore("Markus", 70000);
		insertIntoHighscore("Shelly", 40000);
		Map<String, Long> data = readHighscore();
		for(String key : data.keySet())
		{
			System.out.println(key + " - " + data.get(key));
		}
	}
	
	private static void test2()
	{
		createTable();
		BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
		String input = "";
		do{
			try{
				String name;
				long score;
				System.out.print("Name: ");
				name = reader.readLine();
				System.out.print("Score: ");
				input = reader.readLine();
				score = Long.parseLong(input);
				insertIntoHighscore(name, score);
				System.out.print("Exit? ");
				input = reader.readLine();
			}catch(Exception e){
				System.out.println("Fehler: " + e.getMessage());
			}
		}while(!input.equalsIgnoreCase("exit"));
		Map<String, Long> data = readHighscore();
		for(String key : data.keySet())
		{
			System.out.println(key + " - " + data.get(key));
		}
	}
}
